# NumPy

Numeric Python

In [ ]:
list - collection of different type of elements -> [10, 'goa', 11.5]
- memory allocation is not continuous              id(10)

array - collection of similar type of elements -> [10,20,30,40]
- memory allocation is continuous                 2011,2013, 2015....

In [1]:
!pip install numpy

### 1 - Creating a vector

In [2]:
import numpy as np

In [4]:
# help(np)

In [5]:
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [6]:
print(type(v))

<class 'numpy.ndarray'>


In [7]:
v = np.array([[1],[2],[3]])

v

array([[1],
       [2],
       [3]])

### 2 - Matrix

In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
0th dimension -------->          .
1th dimension -------->          .___________.
2nd dimension -------->          .______|______.
3rd dimension -------->          .______|______.
                                       /

4th dimension ---------> 
.
.
.
.
nth dimension

In [ ]:
images or videos

In [ ]:
1080px
720px

### 3 - Describe Matrix

In [10]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matrix.shape

(3, 3)

In [12]:
matrix.size

9

In [13]:
matrix.ndim

2

### 4 - Max and Min Values

In [14]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
print(np.max(matrix))

9


In [16]:
print(np.min(matrix))

1


In [17]:
print(np.max(matrix, axis = 0)) # columns

[7 8 9]


In [18]:
print(np.max(matrix, axis = 1)) # rows

[3 6 9]


In [19]:
print(np.max(matrix, axis = 1)[0])  # a[0]

3


### 5 - Statistics

In [ ]:
1 - Descriptive - mean, median, mode, standard deviation, variance, IQR, percentile

2 - Inferential - models, hypothesis testing, regression(relationship)

In [21]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print(np.mean(matrix))

5.0


In [23]:
print(np.std(matrix))

2.581988897471611


In [24]:
print(np.var(matrix))

6.666666666666667


### 6 - Reshaping arrays

In [25]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
print(matrix.reshape(9))

[1 2 3 4 5 6 7 8 9]


In [27]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [28]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [29]:
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


In [ ]:
while :
    while :
        while:

n square

n cube


### 7 - Selecting Elements

In [30]:
#             -7 -6 -5 -4 -3 -2 -1
v = np.array([11,12,13,14,15,16,17])
#             0   1  2  3  4  5  6
print(v[0])

11


In [31]:
print(v[5])

16


In [32]:
print(v[-1])
print(v[6])

17
17


In [33]:
print(v[3:6])      # v[start : ending]

[14 15 16]


In [34]:
print(v[2:5])

[13 14 15]


In [35]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
00  01  02
10  11  12
20  21  22

In [36]:
print(matrix[0,0])

1


In [37]:
print(matrix[2,1])

8
